### PR TITLE
Add `project_id` parameter to datasets.open function

### PR DESCRIPTION
**Pull request by liamcoatman**

### CODE REVIEW

**Comment by acroz** [comment]
@liamcoatman - The changes I mentioned above are now complete.

Can you please rebase this off master and do a little manual testing to verify it still works as expected?

**Comment by liamcoatman** [comment]
@acroz I rebased and manually verified that it works as expected. Can you have a look at the tests? They are failing and I don't understand why.

**Comment by acroz** [comment]
Hmm yeah the tests appear to be broken on master too. Not sure why just yet.

**Comment by acroz** [comment]
Merged a fix to the tests in #143 - can you rebase off master?

**Comment by liamcoatman** [comment]
@acroz I rebased and the tests are now passing. Can we merge?

**Comment by acroz** [comment]
Thanks - have released this with 0.25.5.

**Pull request merged**
